version: '2'

services:
  db:
    image: postgres
    restart: always
    container_name: flashcards_db
    env_file: .env
    expose:
      - "5432"
  web:
    build: .
    restart: always
    container_name: flashcards_django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file: .env
    ports:
      - "80:8000"
    depends_on:
      - db
