# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='flashcards',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Deck'),
            preserve_default=False,
        ),
    ]
