# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170725_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='type',
            field=models.IntegerField(choices=[(1, 'Klasyczna fiszka'), (2, 'Zdanie do uzupełnienia')], default=1),
        ),
    ]
