# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User
import django.db.models.deletion


def create_profiles(apps, schemaeditor):
    Profile = apps.get_model('main', 'Profile')
    for user in User.objects.all():
        profile = Profile.objects.create(user=user)
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_auto_20170804_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.BooleanField(default=False)),
                ('daily_limit_count', models.IntegerField(default=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_profiles),
    ]
