# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='daily_limit_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='session_limit',
            field=models.BooleanField(default=False, verbose_name='Włącz limit słówek'),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_limit_count',
            field=models.IntegerField(default=50, verbose_name='Liczba słówek na sesję'),
        ),
    ]
