# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170717_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='ef',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='interval',
            field=models.IntegerField(default=1),
        ),
    ]
