# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170717_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='repeated',
            field=models.BooleanField(default=False),
        ),
    ]
