# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170717_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.CharField(max_length=256, verbose_name='Odpowiedź'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='interval',
            field=models.IntegerField(default=1, verbose_name='Interwał'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.CharField(max_length=256, verbose_name='Pytanie'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='repeat',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Dzień powtórki'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
