# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_basic_languages(apps, schema_editor):
    Language = apps.get_model('main', 'Language')
    languages = {
        'polski': 'ĄąĆćĘęŁłŃńÓóŚśŹż',
        'niemiecki': 'ÄäÖöÜüß',
        'angielski': '',
    }
    for lang in languages:
        Language.objects.create(name=lang, special_characters=languages[lang])


def add_basic_decks(apps, schema_editor):
    Deck = apps.get_model('main', 'Deck')
    Flashcard = apps.get_model('main', 'Flashcard')
    Language = apps.get_model('main', 'Language')
    User = apps.get_model('auth', 'User')
    lang = Language.objects.get(name='niemiecki')
    for user in User.objects.all():
        deck = Deck.objects.create(name='niemiecki ogólny', user=user, language=lang)
        flashcards = Flashcard.objects.filter(user=user.id)
        flashcards.update(deck=deck)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20170804_1101'),
    ]

    operations = [
        migrations.RunPython(add_basic_languages),
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Deck', verbose_name='Talia'),
        ),
        migrations.RunPython(add_basic_decks),
        migrations.AlterField(
            model_name='flashcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Deck', verbose_name='Talia'),
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='user',
        ),
    ]
